name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - databricks_cli==0.18.0
  - python=3.9
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
      - databricks_cli==0.8.7
      - wandb==0.13.9
      - mlflow==2.8.1