name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - pip:
<<<<<<< HEAD
      - databricks_cli==0.8.7
      - wandb==0.13.9
=======
      - mlflow==2.8.1
      - wandb==0.16.0
>>>>>>> 0936351046db1e8e7587aa16f516b26a9374b3da
