name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - requests=2.24.0
  - scikit-learn=1.3.2
  - pandas=2.1.3
  - pip:
<<<<<<< HEAD
      - databricks_cli==0.8.7
      - wandb==0.13.9
=======
      - mlflow==2.8.1
      - wandb==0.16.0
>>>>>>> 0936351046db1e8e7587aa16f516b26a9374b3da
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components
