name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pandas=2.1.3
  - pip:
<<<<<<< HEAD
      - wandb==0.16
      - databricks_cli==0.8.7
=======
      - wandb==0.16.0
>>>>>>> 0936351046db1e8e7587aa16f516b26a9374b3da
